# Generated by Django 4.2.29 on 2026-03-07 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('lost', '失物'), ('found', '拾物')], db_index=True, max_length=16)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('category', models.CharField(choices=[('electronics', '电子产品'), ('id', '证件'), ('books', '书籍'), ('daily', '生活用品'), ('other', '其他')], db_index=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(db_index=True, max_length=100)),
                ('time', models.DateTimeField(help_text='丢失/拾到时间')),
                ('contact', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/%Y/%m/')),
                ('status', models.CharField(choices=[('open', '未找回/未认领'), ('closed', '已完成')], db_index=True, default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
