# Generated by Django 4.2.30 on 2026-04-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('electronics', '电子产品'), ('id', '证件卡片'), ('books', '书籍资料'), ('daily', '生活用品'), ('other', '其他物品')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('open', '待认领'), ('closed', '已完成')], db_index=True, default='open', max_length=16),
        ),
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.DateTimeField(help_text='物品遗失或拾获的时间'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('lost', '失物'), ('found', '招领')], db_index=True, max_length=16),
        ),
    ]
